{
  products{
    _id
    title
    short_text
    text
    tags
    images
    category {
      title
      _id
    }
    features {
      height
      width
      weight
      length
      
    }
    comments{
      _id
      comment
      user {
        first_name
        last_name
      }
    }
     bookmarks{
      first_name
      last_name
      _id
    }
    likes{
       first_name
      last_name
      _id 
    }
  }
}